# Generated by Django 5.1.6 on 2025-02-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('photo', models.ImageField(upload_to='applicant_photos/')),
                ('pan_no', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_no', models.CharField(max_length=50, unique=True)),
                ('shop_name', models.CharField(max_length=255)),
                ('trade_type', models.CharField(max_length=100)),
                ('trade_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shop_address', models.TextField()),
                ('building_ownership', models.CharField(max_length=20)),
                ('building_owner_name', models.CharField(max_length=255)),
                ('building_owner_phone', models.CharField(max_length=15)),
                ('id_proof', models.FileField(upload_to='license_documents/id_proofs/')),
                ('building_proof', models.FileField(upload_to='license_documents/building_proofs/')),
                ('other_documents', models.FileField(blank=True, null=True, upload_to='license_documents/others/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ISSUED', 'Issued'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('DUE', 'Due Renewal')], default='PENDING', max_length=20)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicants', models.ManyToManyField(related_name='trade_licenses', to='vyapara.applicant')),
            ],
        ),
    ]
